name: mnn_release
on:
  push:
    branches:
        - 'feature/**'
jobs:
  setup:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - name: get-version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

  windows-release:
    needs: [setup]
    runs-on: windows-latest
    env:
      PACKAGENAME: mnn_${{ needs.setup.outputs.VERSION }}_windows_x64_cpu_opencl
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: using msvc
      uses: ilammy/msvc-dev-cmd@v1

    - name: build
      run: powershell .\package_scripts\win\build_lib_release.ps1 -path test