name: pymnn_release
on:
  push:
    branches:
        - 'feature/**'
jobs:
  build_wheels:
    name: ${{ matrix.arch }} ${{ matrix.build }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: windows-latest,   arch: AMD64,      build: 'cp*'          }

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: using msvc
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.4
      env:
        CIBW_ARCHS_MACOS: ${{ matrix.arch }}
        CIBW_ARCHS_LINUX: ${{ matrix.arch }}
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.build }}
        CIBW_SKIP: cp311-*
        CIBW_BUILD_VERBOSITY: 1
        CIBW_ENVIRONMENT: CMAKE_BUILD_PARALLEL_LEVEL=2
      with:
        package-dir: pymnn/pip_package
        output-dir: wheelhouse
        config-file: "{package}/pyproject.toml"

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl